### ISSUE TITLE
"missing 1 required positional argument: 'options'" when try to save the file

### ISSUE THREAD

**Issue by NosgothicRealm** [iamironman0/OpenAI-Whisper-GUI#1]
Hello! 
First, thank you so much for the Whisper's GUI

I'm not too expert using Python and I got this error after the task was finished and I tried to save the transcripted file:
`"C:\ProgramData\Anaconda3\envs\offline\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Python\Offline\GUI\main.py", line 733, in save_text
    writer(self.result, file_name)
TypeError: __call__() missing 1 required positional argument: 'options'`

Any idea how to solve this? 
I'm doing something wrong?
I really appreciate any help you can provide.

**Comment by meeksqueal** [comment]
try a fresh install of openai-whisper. it helped in my scenario.

pip uninstall openai-whisper
pip cache purge
pip install openai-whisper

**Comment by NosgothicRealm** [comment]
> try a fresh install of openai-whisper. it helped in my scenario.
> 
> pip uninstall openai-whisper pip cache purge pip install openai-whisper

Thank you so much! 
Those steps solve the issue :) !
