### ISSUE TITLE
No matching distribution found for customtkinter

### ISSUE THREAD

**Issue by danilo139** [iamironman0/OpenAI-Whisper-GUI#10]
im having the following error in the last step

ERROR: Could not find a version that satisfies the requirement customtkinter (from versions: none)
ERROR: No matching distribution found for customtkinter

Last version of python and pip is installed

**Comment by iamironman0** [comment]
Which python version do you use? try this:

`pip3 install customtkinter==0.3`

Also check the new Whisper Transcriber app:
https://github.com/iamironman0/Whisper-Transcriber

**Comment by danilo139** [comment]
no im having this one:

ERROR: Could not find a version that satisfies the requirement pynvml (from versions: none)
ERROR: No matching distribution found for pynvml
