### ISSUE TITLE
Error opening icon file

### ISSUE THREAD

**Issue by jazzynico** [iamironman0/OpenAI-Whisper-GUI#4]
First of all thanks for your effort in sharing a nice UI for Whisper!

My system and applications: 
- Xubuntu 22.04.3 LTS,
- Python3 3.10.12. GUI,
- Whisper and all dependencies installed, as user (not for the whole system).

I'm running into an annoying issue that happens when launching the application.
The UI doesn't show, and the application crashes with the following traceback (paths changed for readability):
```
$ python3 main.py 
Traceback (most recent call last):
  File "/home/nicolas/Python/OpenAI-Whisper-GUI/main.py", line 804, in <module>
    app = WhisperGui()
  File "/home/nicolas/Python/OpenAI-Whisper-GUI/main.py", line 185, in __init__
    self.iconbitmap(app_logo)
  File "/home/nicolas/.local/lib/python3.10/site-packages/customtkinter/windows/ctk_tk.py", line 230, in iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "./icons/logo.ico" not defined
```
I managed to workaround the issue by `self.iconbitmap(app_logo)` line, and the application launched nicely.

Changing the icon path with app_logo = "@/home/nicolas/Python/OpenAI-Whisper-GUI/icons/logo.ico" (tried with and without the @ at the beginning of the line) doesn't work either, but the error message is different:
_tkinter.TclError: error reading bitmap file `app_logo = "@/home/nicolas/Python/OpenAI-Whisper-GUI/icons/logo.ico"`
which seems to mean that the file is not a supported format.

The I saw this: https://stackoverflow.com/questions/11176638/tkinter-tclerror-error-reading-bitmap-file
and indeed, converting the ico file to xbm, along with changing the relative path to an absolute one, works perfectly!

Don't hesitate if you need further information or testing, in case the issue is very specific to my platform.

Thanks!

**Comment by jazzynico** [comment]
Quick and dirty fix, tested locally. Git diff attached.
[iconbitmap.diff.txt](https://github.com/iamironman0/OpenAI-Whisper-GUI/files/12777683/iconbitmap.diff.txt)

Can possibly be done with Path to be more Python3, but I'm not sure how to handle the prepended @.

**Comment by iamironman0** [comment]
@jazzynico Try this method:

current_directory = os.path.dirname(os.path.abspath(__file__))
app_logo = os.path.join(current_directory, "icons/logo.ico")

**Comment by Vic-s** [comment]
```
current_directory = os.getcwd()
app_logo = os.path.join(current_directory, "icons/logo.ico")
```

But this does not solve the issue. My workaround :
app_logo = ""
