### ISSUE TITLE
Model size stuck with GPU check values

### ISSUE THREAD

**Issue by jazzynico** [iamironman0/OpenAI-Whisper-GUI#5]
My system and applications:

    Xubuntu 22.04.3 LTS,
    Python3 3.10.12. GUI,
    Whisper and all dependencies installed, as user (not for the whole system).

Since my graphic card is a bit short in memory (2 Gio), I'd like to use a medium model with my CPU (even if it's going to take some time).
GPU check is done at startup and the Model Size list set accordingly. and there's no possibility to access bigger models, even after setting device to CPU.
It would be great if setting CPU could reset the model size (another check could be done each time GPU is selected again).

Thanks!

**Comment by iamironman0** [comment]
Thanks for feedback, there will be not update to this app anymore however i am working on a brand new Whisper GUI app.

**Comment by jazzynico** [comment]
> Thanks for feedback, there will be not update to this app anymore however i am working on a brand new Whisper GUI app.

Great! I'm eager to see it online!
